data_folder: "/home/justin/data/contact_data/train/numpy/"
model_load_path: "/home/justin/code/deep-contact-estimator/results/0913_auto_contact_best_val_loss.pt"
# model_load_path: "/home/justin/code/deep-contact-estimator/results/0616_2blocks_best_val_loss.pt"

# data params
window_size: 150

# network params
batch_size: 30

save_to_mat: False
mat_save_path: "/home/justin/code/deep-contact-estimator/results/0913_auto_contact_best_val_loss.mat"

